apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
  labels:
    app: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: master
          image: takeover
          imagePullPolicy: Never # Need this when using local images
          command: ["python"]
          args: ["main.py", "master"]
        
