apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    run: rabbitmq
spec:
  ports:
  - port: 5672
    name: "messages"
    protocol: TCP
  - port: 15672
    name: "ui"
    protocol: TCP
  selector:
    app: rabbitmq
