apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image:  357830361939.dkr.ecr.us-east-2.amazonaws.com/genetic:worker
          #imagePullPolicy: Never # Need this when using local images
          command: ["python"]
          args: ["main.py", "worker"]
