apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image:  357830361939.dkr.ecr.us-east-2.amazonaws.com/genetic:worker-amd64
          #imagePullPolicy: Never # Need this when using local images
          imagePullPolicy: "Always" # so we make sure to update image code changes 
          command: ["python"]
          args: ["main.py", "worker"]
      nodeSelector:
        # to figure this out, we can run 
        # $ kubectl get nodes --show-labels
        alpha.eksctl.io/nodegroup-name: worker-ng
